services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_lab_report

  laboratoryreport-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/db_lab_report
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  
  laboratoryreport-frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - laboratoryreport-backend